version: 0.0
os: linux


files:             
  - source: /csye6225-fall2018-lambda/webapp/Assignment_4/target/webapi_assignment3-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/webapps

hooks:
  AfterInstall:
   - location: ./afterInstall.sh

     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 180
     runas: centos

  # ValidateService:
  #  - location: ./validateService.sh
  #    timeout: 180
#    runas: centos

